server:
  port: 7001

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

---
spring:
  config:
    activate:
      on-profile: docker

server:
  port: 8080