services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5673:5672"  # Cambia la porta esterna a 5673
      - "15673:15672"  # Cambia la porta esterna a 15673
  listener-service:
    build: ./listener-service
    depends_on:
      - rabbitmq
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
  consumer-service:
    build: ./consumer-service
    depends_on:
      - rabbitmq
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
